# Generated by Django 3.2.4 on 2021-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='SUN', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dropped', models.BooleanField(default=False)),
                ('completed_reading', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='authors', to='api.Author')),
                ('days_of_release', models.ManyToManyField(related_name='days_of_release', to='api.DayOfRelease')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='webtoons',
            field=models.ManyToManyField(related_name='webtoons', to='api.Webtoon'),
        ),
    ]
