# Generated by Django 3.2.4 on 2021-06-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dayofrelease_webtoons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='webtoons',
        ),
        migrations.RemoveField(
            model_name='dayofrelease',
            name='webtoons',
        ),
    ]
